name: qtclass_studio
description: "量潮课堂客户端"
publish_to: "none"
version: 0.1.1

environment:
  sdk: ^3.11.5

dependencies:
  http: ^1.2.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.2.0
  quanttide_course: ^0.1.1
  video_player: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/course.json
    - assets/videos/
