name: qtclass_studio
description: "量潮课堂 - 课程与学员管理"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  quanttide_course:
    git:
      url: https://github.com/quanttide/quanttide-course-toolkit.git
      path: packages/dart
      ref: beaedcdc741acf3cc9fcc1655b8cc88a189c5f58

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sessions.json
    - assets/lectures.json
